[files]
current_page=-1
recent_files=/home/cobra/Workspace/c/nex/src/desktop.c;/home/cobra/Workspace/c/nex/src/events.c;/home/cobra/Workspace/c/nex/src/ewmh.c;/home/cobra/Workspace/c/nex/src/geometry.c;/home/cobra/Workspace/c/nex/src/helpers.c;/home/cobra/Workspace/c/nex/src/history.c;/home/cobra/Workspace/c/nex/src/jsmn.c;/home/cobra/Workspace/c/nex/src/messages.c;/home/cobra/Workspace/c/nex/src/monitor.c;/home/cobra/Workspace/c/nex/src/nex.c;
recent_projects=

[VTE]
last_dir=/home/liveuser

[project]
session_file=
project_file_path=

[geany]
treeview_position=156
msgwindow_position=472
geometry=10;34;1342;720;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=true
position_find_x=865
position_find_y=615
position_replace_x=855
position_replace_y=535
position_fif_x=675
position_fif_y=205

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
