#!/usr/bin/env bash


## All windows are floating on desktop 8
FLOATING_DESKTOP_ID=$(nexl query -D -d '^8')

nexl subscribe node_add | while read -a msg ; do
   desk_id=${msg[2]}
   wid=${msg[4]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && nexl node "$wid" -t floating
done
