#!/usr/bin/env bash

##
## Run ncmpcpp with alternate config

# nex directory
DIR="$HOME/.config/nex"

CONFIG="$DIR/alacritty/alacritty.toml"

alacritty --class 'Music,Music' --config-file "$CONFIG" \
		  -o window.dimensions.columns=105 window.dimensions.lines=22 \
		  -e ~/.ncmpcpp/scripts/ncmpcpp-art
